# Generated by Django 5.1.4 on 2024-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="phone1",
        ),
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.TextField(default="No address provided"),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone2",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
