# Generated by Django 5.1.4 on 2024-12-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_rename_name_contact_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["first_name"], name="contacts_co_first_n_011199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["last_name"], name="contacts_co_last_na_12cfae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="contacts_co_email_25f973_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["phone1"], name="contacts_co_phone1_31b51a_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["phone2"], name="contacts_co_phone2_3f7fa8_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["address"], name="contacts_co_address_775b01_idx"
            ),
        ),
    ]
