# Generated by Django 5.1.4 on 2024-12-16 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contact_deleted_alter_contact_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="deleted",
        ),
    ]
